title: vukienha.github.io
author: Hà Vũ kiên
email: vukienha@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Blog cá nhân nhằm lưu trữ và chia sẽ kiến thức về công nghệ, lập trình
# social links
#twitter_username: jekyllrb
github_username:  vukienha
rss: rss
#dribbble_username: jekyll
#facebook_username: https://facebook.com/havukien
#flickr_username: jekyll
#instagram_username: jekyll
#linkedin_username: jekyll
#pinterest_username: jekyll
#youtube_username: jekyll
#googleplus_username: +jekyll

show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock